test falco 25

diff --git a/.github/workflows/workflowaction.yml b/.github/workflows/workflowaction.yml
--- a/.github/workflows/workflowaction.yml
+++ b/.github/workflows/workflowaction.yml
@@ -75,12 +75,13 @@ jobs:
         - name: Run Docker container with Falco monitoring # BƯỚC 2: FALCO GIÁM SÁT CONTAINER ỨNG DỤNG
           run: |
             docker build -t vulnerable-app:latest -f ./Dockerfile .
-            docker run -d --name app-container -v $(pwd):/app vulnerable-app:latest node src/server/app.js || {
-            echo "Failed to run container. Check logs for details."
-            exit 1
+            docker run -d --rm --name app-container vulnerable-app:latest npm start || {
+              echo "Failed to start app-container, checking logs..."
+              docker logs app-container > app_container_logs.txt 2>&1
+              cat app_container_logs.txt
+              exit 1
             }
             sleep 60
-            docker stop app-container || true
             docker ps -a
         - name: Check Falco logs for alerts
           run: |
